#!/bin/bash

echo "🚀 SEO Dashboard Deployment Script"
echo "=================================="
echo ""

# Change to the project directory
cd "/Users/samwilhoit/Documents/seo tool/seo_dashboard"

echo "📍 Current directory: $(pwd)"
echo ""

echo "🔧 Step 1: Railway CLI Setup"
echo "----------------------------"
echo "Please run the following commands manually:"
echo ""
echo "1. Login to Railway:"
echo "   railway login"
echo ""
echo "2. Link to your existing project:"
echo "   railway link"
echo ""
echo "3. Get your Railway URL:"
echo "   railway domain"
echo ""
echo "4. Check deployment status:"
echo "   railway status"
echo ""

echo "🌐 Step 2: Vercel CLI Setup"
echo "---------------------------"
echo "Please run the following commands manually:"
echo ""
echo "1. Login to Vercel:"
echo "   vercel login"
echo ""
echo "2. Deploy frontend (from project root):"
echo "   vercel --cwd frontend"
echo ""
echo "3. Set environment variable (replace YOUR_RAILWAY_URL):"
echo "   vercel env add REACT_APP_API_URL"
echo "   # Enter: https://YOUR_RAILWAY_URL.railway.app"
echo ""

echo "🔍 Step 3: Test Your Deployments"
echo "--------------------------------"
echo "After deployment, test these URLs:"
echo ""
echo "Railway Backend Health Check:"
echo "   curl https://YOUR_RAILWAY_URL.railway.app/ping"
echo "   # Should return: pong"
echo ""
echo "Vercel Frontend:"
echo "   # Visit your Vercel URL in browser"
echo ""

echo "✅ Complete Setup Commands:"
echo "==========================="
echo ""
echo "# Railway setup:"
echo "railway login"
echo "railway link"
echo "railway domain"
echo ""
echo "# Vercel setup:"
echo "vercel login"
echo "vercel --cwd frontend"
echo "vercel env add REACT_APP_API_URL"
echo ""

echo "💡 Tips:"
echo "--------"
echo "- Railway URL: Use the full domain (https://your-app.railway.app)"
echo "- Vercel root: Set to 'frontend' directory"
echo "- Test Railway: /ping should return 'pong'"
echo ""

echo "📋 Next Steps:"
echo "1. Run the Railway commands above"
echo "2. Note your Railway URL"
echo "3. Run the Vercel commands above"
echo "4. Set REACT_APP_API_URL to your Railway URL"
echo "5. Test both deployments"
echo ""

echo "🎉 Your SEO Dashboard will be fully deployed!"