[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "cd backend",
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && . /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"