[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate", 
    "pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"